---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./configuration

patches:
- target:
    labelSelector: flux2-kind/phase=init
  patch: |-
    apiVersion: any
    kind: any
    metadata:
      name: any
    $patch: delete